from __future__ import annotations

import os

os.environ["DATABASE_URL"] = "sqlite+pysqlite:///:memory:"

from fastapi.testclient import TestClient

from app.database import Base, SessionLocal, engine
from app.main import app
from app.seed import seed_database


def _reset_database() -> None:
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        seed_database(db)
    finally:
        db.close()


def _client() -> TestClient:
    _reset_database()
    return TestClient(app)


def _create_service(client: TestClient, slug: str = "search-service") -> dict:
    response = client.post(
        "/api/services",
        json={
            "name": "Search Service",
            "slug": slug,
            "description": "Indexes service and incident data.",
            "environment": "staging",
            "status": "healthy",
            "owner": "qa-team",
        },
    )
    assert response.status_code == 201
    return response.json()


def test_health_endpoint() -> None:
    with _client() as client:
        response = client.get("/health")

    assert response.status_code == 200
    assert response.json() == {"status": "ok", "service": "opsforge"}


def test_metrics_endpoint_exposes_prometheus_metrics() -> None:
    with _client() as client:
        health_response = client.get("/health")
        metrics_response = client.get("/metrics")

    assert health_response.status_code == 200
    assert metrics_response.status_code == 200
    assert metrics_response.headers["content-type"].startswith("text/plain")
    assert "opsforge_http_requests_total" in metrics_response.text
    assert "opsforge_http_request_duration_seconds_bucket" in metrics_response.text
    assert 'method="GET"' in metrics_response.text
    assert 'route="/health"' in metrics_response.text
    assert 'status_code="200"' in metrics_response.text
    assert 'route="/metrics"' not in metrics_response.text


def test_dashboard_renders() -> None:
    with _client() as client:
        response = client.get("/dashboard")

    assert response.status_code == 200
    assert "OpsForge" in response.text


def test_create_service() -> None:
    with _client() as client:
        service = _create_service(client)
        response = client.get(f"/api/services/{service['id']}")

    assert response.status_code == 200
    assert response.json()["slug"] == "search-service"


def test_create_alert() -> None:
    with _client() as client:
        service = _create_service(client)
        response = client.post(
            "/api/alerts",
            json={
                "service_id": service["id"],
                "source": "pytest",
                "title": "Synthetic warning",
                "message": "A warning generated by the test suite.",
                "severity": "warning",
            },
        )

    assert response.status_code == 201
    body = response.json()
    assert body["service_id"] == service["id"]
    assert body["status"] == "new"


def test_create_incident_linked_to_alert() -> None:
    with _client() as client:
        service = _create_service(client)
        alert_response = client.post(
            "/api/alerts",
            json={
                "service_id": service["id"],
                "source": "pytest",
                "title": "Critical alert",
                "message": "A critical alert generated by the test suite.",
                "severity": "critical",
            },
        )
        alert = alert_response.json()

        incident_response = client.post(
            "/api/incidents",
            json={
                "source_alert_id": alert["id"],
                "title": "Incident from alert",
                "description": "The service is failing under test.",
                "severity": "high",
            },
        )

    assert incident_response.status_code == 201
    incident = incident_response.json()
    assert incident["source_alert_id"] == alert["id"]
    assert incident["service_id"] == service["id"]


def test_execute_runbook() -> None:
    with _client() as client:
        response = client.post(
            "/api/runbooks/health_check_service/execute",
            json={"requested_by": "pytest"},
        )

    assert response.status_code == 200
    body = response.json()
    assert body["status"] == "success"
    assert body["requested_by"] == "pytest"
    assert "Checked" in body["output"]


def test_runbook_execution_creates_audit_log() -> None:
    with _client() as client:
        execution_response = client.post(
            "/api/runbooks/simulate_backup_check/execute",
            json={"requested_by": "pytest"},
        )
        execution = execution_response.json()
        logs_response = client.get("/api/audit-logs")

    assert execution_response.status_code == 200
    assert logs_response.status_code == 200
    assert any(
        log["action"] == "runbook.executed"
        and log["entity_type"] == "RunbookExecution"
        and log["entity_id"] == execution["id"]
        for log in logs_response.json()
    )
