from __future__ import annotations

import os

os.environ["DATABASE_URL"] = "sqlite+pysqlite:///:memory:"

from fastapi.testclient import TestClient

from app.database import Base, SessionLocal, engine
from app.main import app
from app.seed import seed_database


def _reset_database() -> None:
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        seed_database(db)
    finally:
        db.close()


def _client() -> TestClient:
    _reset_database()
    return TestClient(app)


def _create_service(client: TestClient, slug: str = "search-service") -> dict:
    response = client.post(
        "/api/services",
        json={
            "name": "Search Service",
            "slug": slug,
            "description": "Indexes service and incident data.",
            "environment": "staging",
            "status": "healthy",
            "owner": "qa-team",
        },
    )
    assert response.status_code == 201
    return response.json()


def test_health_endpoint() -> None:
    with _client() as client:
        response = client.get("/health")

    assert response.status_code == 200
    assert response.json() == {"status": "ok", "service": "opsforge"}


def test_readiness_endpoint() -> None:
    with _client() as client:
        response = client.get("/ready")

    assert response.status_code == 200
    assert response.json() == {"status": "ready", "service": "opsforge"}


def test_metrics_endpoint_exposes_prometheus_metrics() -> None:
    with _client() as client:
        health_response = client.get("/health")
        metrics_response = client.get("/metrics")

    assert health_response.status_code == 200
    assert metrics_response.status_code == 200
    assert metrics_response.headers["content-type"].startswith("text/plain")
    assert "opsforge_http_requests_total" in metrics_response.text
    assert "opsforge_http_request_duration_seconds_bucket" in metrics_response.text
    assert 'method="GET"' in metrics_response.text
    assert 'route="/health"' in metrics_response.text
    assert 'status_code="200"' in metrics_response.text
    assert 'route="/metrics"' not in metrics_response.text


def test_dashboard_renders() -> None:
    with _client() as client:
        response = client.get("/dashboard")

    assert response.status_code == 200
    assert "OpsForge" in response.text
    assert "Operator console" in response.text
    assert "Incident workspace" in response.text
    assert "Recent runbook activity" in response.text
    assert "data-operator-tab" in response.text
    assert "data-operator-form=\"service\"" in response.text
    assert "data-operator-form=\"alert\"" in response.text
    assert "data-operator-form=\"incident\"" in response.text
    assert "data-incident-status-action" in response.text
    assert "data-runbook-execute" in response.text


def test_create_service() -> None:
    with _client() as client:
        service = _create_service(client)
        response = client.get(f"/api/services/{service['id']}")

    assert response.status_code == 200
    assert response.json()["slug"] == "search-service"


def test_create_alert() -> None:
    with _client() as client:
        service = _create_service(client)
        response = client.post(
            "/api/alerts",
            json={
                "service_id": service["id"],
                "source": "pytest",
                "title": "Synthetic warning",
                "message": "A warning generated by the test suite.",
                "severity": "warning",
            },
        )

    assert response.status_code == 201
    body = response.json()
    assert body["service_id"] == service["id"]
    assert body["status"] == "new"


def test_dashboard_lists_actionable_alert_context() -> None:
    with _client() as client:
        service = _create_service(client, slug="operator-service")
        alert_response = client.post(
            "/api/alerts",
            json={
                "service_id": service["id"],
                "source": "operator-test",
                "title": "Operator alert",
                "message": "An alert that should be available to the operator.",
                "severity": "critical",
            },
        )
        alert = alert_response.json()
        dashboard_response = client.get("/dashboard")

    assert dashboard_response.status_code == 200
    assert f'data-alert-id="{alert["id"]}"' in dashboard_response.text
    assert f'value="{alert["id"]}"' in dashboard_response.text
    assert "Operator alert" in dashboard_response.text
    assert "Search Service" in dashboard_response.text


def test_alert_status_actions_used_by_operator_console() -> None:
    with _client() as client:
        service = _create_service(client, slug="alert-action-service")
        alert_response = client.post(
            "/api/alerts",
            json={
                "service_id": service["id"],
                "source": "operator-test",
                "title": "Actionable alert",
                "message": "An alert used to verify operator actions.",
                "severity": "warning",
            },
        )
        alert = alert_response.json()

        acknowledge_response = client.patch(
            f"/api/alerts/{alert['id']}/acknowledge"
        )
        resolve_response = client.patch(f"/api/alerts/{alert['id']}/resolve")

    assert acknowledge_response.status_code == 200
    assert acknowledge_response.json()["status"] == "acknowledged"
    assert resolve_response.status_code == 200
    assert resolve_response.json()["status"] == "resolved"
    assert resolve_response.json()["resolved_at"] is not None


def test_create_incident_linked_to_alert() -> None:
    with _client() as client:
        service = _create_service(client)
        alert_response = client.post(
            "/api/alerts",
            json={
                "service_id": service["id"],
                "source": "pytest",
                "title": "Critical alert",
                "message": "A critical alert generated by the test suite.",
                "severity": "critical",
            },
        )
        alert = alert_response.json()

        incident_response = client.post(
            "/api/incidents",
            json={
                "source_alert_id": alert["id"],
                "title": "Incident from alert",
                "description": "The service is failing under test.",
                "severity": "high",
            },
        )

    assert incident_response.status_code == 201
    incident = incident_response.json()
    assert incident["source_alert_id"] == alert["id"]
    assert incident["service_id"] == service["id"]


def test_create_incident_rejects_service_conflicting_with_source_alert() -> None:
    with _client() as client:
        alert_service = _create_service(client, slug="alert-service")
        other_service = _create_service(client, slug="other-service")
        alert_response = client.post(
            "/api/alerts",
            json={
                "service_id": alert_service["id"],
                "source": "pytest",
                "title": "Critical alert",
                "message": "A critical alert generated by the test suite.",
                "severity": "critical",
            },
        )
        alert = alert_response.json()

        response = client.post(
            "/api/incidents",
            json={
                "service_id": other_service["id"],
                "source_alert_id": alert["id"],
                "title": "Conflicting incident",
                "severity": "high",
            },
        )

    assert response.status_code == 409
    assert response.json()["detail"] == "Incident service must match the source alert service."


def test_incident_status_updates_used_by_dashboard_actions() -> None:
    with _client() as client:
        service = _create_service(client, slug="status-service")
        incident_response = client.post(
            "/api/incidents",
            json={
                "service_id": service["id"],
                "title": "Dashboard status incident",
                "severity": "high",
            },
        )
        incident = incident_response.json()

        investigating_response = client.patch(
            f"/api/incidents/{incident['id']}/status",
            json={"status": "investigating"},
        )
        resolved_response = client.patch(
            f"/api/incidents/{incident['id']}/status",
            json={"status": "resolved"},
        )

    assert investigating_response.status_code == 200
    assert investigating_response.json()["status"] == "investigating"
    assert resolved_response.status_code == 200
    assert resolved_response.json()["status"] == "resolved"
    assert resolved_response.json()["resolved_at"] is not None


def test_execute_runbook() -> None:
    with _client() as client:
        response = client.post(
            "/api/runbooks/health_check_service/execute",
            json={"requested_by": "pytest"},
        )

    assert response.status_code == 200
    body = response.json()
    assert body["status"] == "success"
    assert body["requested_by"] == "pytest"
    assert "Checked" in body["output"]


def test_runbook_executes_for_related_service_and_incident() -> None:
    with _client() as client:
        service = _create_service(client, slug="runbook-service")
        incident_response = client.post(
            "/api/incidents",
            json={
                "service_id": service["id"],
                "title": "Runbook workspace incident",
                "severity": "high",
            },
        )
        incident = incident_response.json()

        response = client.post(
            "/api/runbooks/generate_incident_report/execute",
            json={
                "service_id": service["id"],
                "incident_id": incident["id"],
                "requested_by": "dashboard-operator",
            },
        )

    assert response.status_code == 200
    execution = response.json()
    assert execution["status"] == "success"
    assert execution["service_id"] == service["id"]
    assert execution["incident_id"] == incident["id"]
    assert f"Incident #{incident['id']}" in execution["output"]


def test_runbook_execution_rejects_unrelated_service_and_incident() -> None:
    with _client() as client:
        incident_service = _create_service(client, slug="incident-service")
        other_service = _create_service(client, slug="unrelated-service")
        incident_response = client.post(
            "/api/incidents",
            json={
                "service_id": incident_service["id"],
                "title": "Service-specific incident",
                "severity": "high",
            },
        )
        incident = incident_response.json()

        execution_response = client.post(
            "/api/runbooks/generate_incident_report/execute",
            json={
                "service_id": other_service["id"],
                "incident_id": incident["id"],
                "requested_by": "pytest",
            },
        )
        logs_response = client.get("/api/audit-logs")

    assert execution_response.status_code == 200
    execution = execution_response.json()
    assert execution["status"] == "failed"
    assert execution["service_id"] is None
    assert execution["incident_id"] == incident["id"]
    assert "does not match" in execution["output"]
    assert any(
        log["action"] == "runbook.executed"
        and log["entity_id"] == execution["id"]
        and '"status": "failed"' in log["details"]
        for log in logs_response.json()
    )


def test_runbook_execution_creates_audit_log() -> None:
    with _client() as client:
        execution_response = client.post(
            "/api/runbooks/simulate_backup_check/execute",
            json={"requested_by": "pytest"},
        )
        execution = execution_response.json()
        logs_response = client.get("/api/audit-logs")

    assert execution_response.status_code == 200
    assert logs_response.status_code == 200
    assert any(
        log["action"] == "runbook.executed"
        and log["entity_type"] == "RunbookExecution"
        and log["entity_id"] == execution["id"]
        for log in logs_response.json()
    )
