from __future__ import annotations

import os

os.environ["DATABASE_URL"] = "sqlite+pysqlite:///:memory:"

from fastapi.testclient import TestClient

from app.database import Base, SessionLocal, engine
from app.main import app
from app.seed import seed_database


def _reset_database() -> None:
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        seed_database(db)
    finally:
        db.close()


def _client() -> TestClient:
    _reset_database()
    return TestClient(app)


def _create_service(client: TestClient, slug: str = "search-service") -> dict:
    response = client.post(
        "/api/services",
        json={
            "name": "Search Service",
            "slug": slug,
            "description": "Indexes service and incident data.",
            "environment": "staging",
            "status": "healthy",
            "owner": "qa-team",
        },
        headers={"X-OpsForge-Actor": "pytest"},
    )
    assert response.status_code == 201
    return response.json()


def _create_alert(
    client: TestClient,
    service_id: int,
    *,
    title: str = "Synthetic warning",
    severity: str = "warning",
) -> dict:
    response = client.post(
        "/api/alerts",
        json={
            "service_id": service_id,
            "source": "pytest",
            "title": title,
            "message": "A signal generated by the test suite.",
            "severity": severity,
        },
        headers={"X-OpsForge-Actor": "pytest"},
    )
    assert response.status_code == 201
    return response.json()


def _create_manual_incident(
    client: TestClient,
    service_id: int,
    *,
    title: str = "Manual test incident",
) -> dict:
    response = client.post(
        "/api/incidents",
        json={
            "service_id": service_id,
            "title": title,
            "description": "An operator-declared incident used by pytest.",
            "severity": "high",
            "owner": "pytest",
        },
        headers={"X-OpsForge-Actor": "pytest"},
    )
    assert response.status_code == 201
    return response.json()


def test_health_endpoint() -> None:
    with _client() as client:
        response = client.get("/health")

    assert response.status_code == 200
    assert response.json() == {"status": "ok", "service": "opsforge"}


def test_readiness_endpoint() -> None:
    with _client() as client:
        response = client.get("/ready")

    assert response.status_code == 200
    assert response.json() == {"status": "ready", "service": "opsforge"}


def test_metrics_endpoint_exposes_prometheus_metrics() -> None:
    with _client() as client:
        health_response = client.get("/health")
        metrics_response = client.get("/metrics")

    assert health_response.status_code == 200
    assert metrics_response.status_code == 200
    assert metrics_response.headers["content-type"].startswith("text/plain")
    assert "opsforge_http_requests_total" in metrics_response.text
    assert "opsforge_http_request_duration_seconds_bucket" in metrics_response.text
    assert 'route="/health"' in metrics_response.text
    assert 'route="/metrics"' not in metrics_response.text


def test_dashboard_renders() -> None:
    with _client() as client:
        response = client.get("/dashboard")

    assert response.status_code == 200
    assert "OpsForge" in response.text
    assert "Operator console" in response.text
    assert "Incident workspace" in response.text
    assert "Recent runbook activity" in response.text


def test_create_service_and_audit_it() -> None:
    with _client() as client:
        service = _create_service(client)
        response = client.get(f"/api/services/{service['id']}")
        logs = client.get("/api/audit-logs").json()

    assert response.status_code == 200
    assert response.json()["slug"] == "search-service"
    assert any(
        log["action"] == "service.created"
        and log["entity_id"] == service["id"]
        and log["actor"] == "pytest"
        for log in logs
    )


def test_update_service_and_audit_changes() -> None:
    with _client() as client:
        service = _create_service(client, slug="service-update")
        response = client.patch(
            f"/api/services/{service['id']}",
            json={"status": "degraded", "owner": "Dyllan"},
            headers={"X-OpsForge-Actor": "operator"},
        )
        logs = client.get("/api/audit-logs").json()

    assert response.status_code == 200
    assert response.json()["status"] == "degraded"
    assert any(
        log["action"] == "service.updated"
        and log["entity_id"] == service["id"]
        and '"status"' in log["details"]
        for log in logs
    )


def test_create_alert_and_audit_it() -> None:
    with _client() as client:
        service = _create_service(client)
        alert = _create_alert(client, service["id"])
        logs = client.get("/api/audit-logs").json()

    assert alert["service_id"] == service["id"]
    assert alert["status"] == "new"
    assert any(
        log["action"] == "alert.created" and log["entity_id"] == alert["id"]
        for log in logs
    )


def test_alert_transitions_are_forward_only() -> None:
    with _client() as client:
        service = _create_service(client, slug="alert-transition")
        alert = _create_alert(client, service["id"])
        acknowledged = client.patch(f"/api/alerts/{alert['id']}/acknowledge")
        resolved = client.patch(f"/api/alerts/{alert['id']}/resolve")
        rejected = client.patch(f"/api/alerts/{alert['id']}/acknowledge")

    assert acknowledged.status_code == 200
    assert acknowledged.json()["status"] == "acknowledged"
    assert resolved.status_code == 200
    assert resolved.json()["status"] == "resolved"
    assert rejected.status_code == 409


def test_dashboard_lists_actionable_alert_context() -> None:
    with _client() as client:
        service = _create_service(client, slug="operator-service")
        alert = _create_alert(
            client,
            service["id"],
            title="Operator alert",
            severity="critical",
        )
        dashboard_response = client.get("/dashboard")

    assert dashboard_response.status_code == 200
    assert f'data-alert-id="{alert["id"]}"' in dashboard_response.text
    assert f'value="{alert["id"]}"' in dashboard_response.text
    assert "Operator alert" in dashboard_response.text
    assert "Search Service" in dashboard_response.text


def test_create_incident_linked_to_alert() -> None:
    with _client() as client:
        service = _create_service(client)
        alert = _create_alert(client, service["id"], severity="critical")
        response = client.post(
            "/api/incidents",
            json={
                "source_alert_id": alert["id"],
                "title": "Incident from alert",
                "description": "The service is failing under test.",
                "severity": "high",
            },
        )

    assert response.status_code == 201
    incident = response.json()
    assert incident["source_alert_id"] == alert["id"]
    assert incident["service_id"] == service["id"]


def test_alert_can_have_only_one_active_incident() -> None:
    with _client() as client:
        service = _create_service(client, slug="single-incident")
        alert = _create_alert(client, service["id"], severity="critical")
        payload = {
            "source_alert_id": alert["id"],
            "title": "First active incident",
            "description": "First incident for the alert.",
            "severity": "critical",
        }
        first = client.post("/api/incidents", json=payload)
        second = client.post("/api/incidents", json={**payload, "title": "Duplicate"})
        active = client.get(f"/api/alerts/{alert['id']}/active-incident")

    assert first.status_code == 201
    assert second.status_code == 409
    assert f"#{first.json()['id']}" in second.json()["detail"]
    assert active.json()["id"] == first.json()["id"]


def test_resolved_alert_incident_can_be_replaced_by_a_new_incident() -> None:
    with _client() as client:
        service = _create_service(client, slug="recurring-problem")
        alert = _create_alert(client, service["id"])
        first = client.post(
            "/api/incidents",
            json={
                "source_alert_id": alert["id"],
                "title": "First occurrence",
                "description": "First occurrence under test.",
                "severity": "high",
            },
        ).json()
        client.patch(
            f"/api/incidents/{first['id']}/status", json={"status": "investigating"}
        )
        client.patch(f"/api/incidents/{first['id']}/status", json={"status": "resolved"})
        second = client.post(
            "/api/incidents",
            json={
                "source_alert_id": alert["id"],
                "title": "Second occurrence",
                "description": "A recurring problem creates a new incident.",
                "severity": "high",
            },
        )

    assert second.status_code == 201
    assert second.json()["id"] != first["id"]


def test_manual_incident_requires_service_and_description() -> None:
    with _client() as client:
        service = _create_service(client, slug="manual-requirements")
        missing_service = client.post(
            "/api/incidents",
            json={"title": "No service", "description": "Missing service", "severity": "high"},
        )
        missing_description = client.post(
            "/api/incidents",
            json={"service_id": service["id"], "title": "No description", "severity": "high"},
        )

    assert missing_service.status_code == 422
    assert missing_description.status_code == 422


def test_create_incident_rejects_service_conflicting_with_source_alert() -> None:
    with _client() as client:
        alert_service = _create_service(client, slug="alert-service")
        other_service = _create_service(client, slug="other-service")
        alert = _create_alert(client, alert_service["id"], severity="critical")
        response = client.post(
            "/api/incidents",
            json={
                "service_id": other_service["id"],
                "source_alert_id": alert["id"],
                "title": "Conflicting incident",
                "description": "Mismatched service context.",
                "severity": "high",
            },
        )

    assert response.status_code == 409
    assert "correspondre" in response.json()["detail"]


def test_incident_transitions_are_forward_only_and_audited() -> None:
    with _client() as client:
        service = _create_service(client, slug="status-service")
        incident = _create_manual_incident(client, service["id"])
        direct_resolve = client.patch(
            f"/api/incidents/{incident['id']}/status", json={"status": "resolved"}
        )
        investigating = client.patch(
            f"/api/incidents/{incident['id']}/status", json={"status": "investigating"}
        )
        resolved = client.patch(
            f"/api/incidents/{incident['id']}/status", json={"status": "resolved"}
        )
        reopened = client.patch(
            f"/api/incidents/{incident['id']}/status", json={"status": "investigating"}
        )
        logs = client.get("/api/audit-logs").json()

    assert direct_resolve.status_code == 409
    assert investigating.json()["status"] == "investigating"
    assert resolved.json()["status"] == "resolved"
    assert resolved.json()["resolved_at"] is not None
    assert reopened.status_code == 409
    assert sum(
        log["action"] == "incident.status_changed" and log["entity_id"] == incident["id"]
        for log in logs
    ) == 2


def test_resolving_incident_does_not_resolve_source_alert() -> None:
    with _client() as client:
        service = _create_service(client, slug="separate-lifecycles")
        alert = _create_alert(client, service["id"])
        incident = client.post(
            "/api/incidents",
            json={
                "source_alert_id": alert["id"],
                "title": "Separate lifecycle incident",
                "description": "Incident and alert stay independent.",
                "severity": "high",
            },
        ).json()
        client.patch(
            f"/api/incidents/{incident['id']}/status", json={"status": "investigating"}
        )
        client.patch(f"/api/incidents/{incident['id']}/status", json={"status": "resolved"})
        alert_response = client.get(f"/api/alerts/{alert['id']}")

    assert alert_response.json()["status"] == "new"


def test_incident_owner_update_is_audited() -> None:
    with _client() as client:
        service = _create_service(client, slug="owner-service")
        incident = _create_manual_incident(client, service["id"])
        response = client.patch(
            f"/api/incidents/{incident['id']}",
            json={"owner": "Dyllan"},
            headers={"X-OpsForge-Actor": "Dyllan"},
        )
        logs = client.get("/api/audit-logs").json()

    assert response.status_code == 200
    assert response.json()["owner"] == "Dyllan"
    assert any(
        log["action"] == "incident.owner_changed"
        and log["entity_id"] == incident["id"]
        for log in logs
    )


def test_execute_automated_runbook_with_required_service() -> None:
    with _client() as client:
        service = _create_service(client, slug="health-runbook")
        response = client.post(
            "/api/runbooks/health_check_service/execute",
            json={"service_id": service["id"], "requested_by": "pytest"},
        )

    assert response.status_code == 200
    assert response.json()["status"] == "success"
    assert "Search Service" in response.json()["output"]


def test_missing_runbook_context_creates_failed_audited_execution() -> None:
    with _client() as client:
        response = client.post(
            "/api/runbooks/health_check_service/execute",
            json={"requested_by": "pytest"},
        )
        logs = client.get("/api/audit-logs").json()

    assert response.status_code == 200
    assert response.json()["status"] == "failed"
    assert any(
        log["action"] == "runbook.executed"
        and log["entity_id"] == response.json()["id"]
        and '"status": "failed"' in log["details"]
        for log in logs
    )


def test_runbook_executes_for_related_service_and_incident() -> None:
    with _client() as client:
        service = _create_service(client, slug="runbook-service")
        incident = _create_manual_incident(client, service["id"])
        response = client.post(
            "/api/runbooks/generate_incident_report/execute",
            json={
                "service_id": service["id"],
                "incident_id": incident["id"],
                "requested_by": "dashboard-operator",
            },
        )

    assert response.status_code == 200
    execution = response.json()
    assert execution["status"] == "success"
    assert execution["service_id"] == service["id"]
    assert execution["incident_id"] == incident["id"]
    assert f"Incident #{incident['id']}" in execution["output"]


def test_runbook_execution_rejects_unrelated_service_and_incident() -> None:
    with _client() as client:
        incident_service = _create_service(client, slug="incident-service")
        other_service = _create_service(client, slug="unrelated-service")
        incident = _create_manual_incident(client, incident_service["id"])
        execution_response = client.post(
            "/api/runbooks/generate_incident_report/execute",
            json={
                "service_id": other_service["id"],
                "incident_id": incident["id"],
                "requested_by": "pytest",
            },
        )
        logs = client.get("/api/audit-logs").json()

    execution = execution_response.json()
    assert execution["status"] == "failed"
    assert execution["service_id"] is None
    assert execution["incident_id"] == incident["id"]
    assert "ne correspond pas" in execution["output"]
    assert any(
        log["action"] == "runbook.executed"
        and log["entity_id"] == execution["id"]
        and '"status": "failed"' in log["details"]
        for log in logs
    )


def test_resolve_runbook_respects_incident_transition_and_audits_it() -> None:
    with _client() as client:
        service = _create_service(client, slug="resolve-runbook")
        incident = _create_manual_incident(client, service["id"])
        rejected = client.post(
            "/api/runbooks/mark_incident_resolved/execute",
            json={"incident_id": incident["id"], "requested_by": "pytest"},
        )
        client.patch(
            f"/api/incidents/{incident['id']}/status", json={"status": "investigating"}
        )
        resolved = client.post(
            "/api/runbooks/mark_incident_resolved/execute",
            json={"incident_id": incident["id"], "requested_by": "pytest"},
        )
        current = client.get(f"/api/incidents/{incident['id']}").json()
        logs = client.get("/api/audit-logs").json()

    assert rejected.json()["status"] == "failed"
    assert resolved.json()["status"] == "success"
    assert current["status"] == "resolved"
    assert any(
        log["action"] == "incident.status_changed"
        and log["entity_id"] == incident["id"]
        and '"to": "resolved"' in log["details"]
        for log in logs
    )


def test_create_and_complete_manual_runbook() -> None:
    with _client() as client:
        service = _create_service(client, slug="manual-runbook-service")
        incident = _create_manual_incident(client, service["id"])
        runbook_response = client.post(
            "/api/runbooks",
            json={
                "key": "verify_demo_dependency",
                "name": "Vérifier une dépendance de démonstration",
                "description": "Manual test runbook.",
                "mode": "manual",
                "instructions": "Confirm each step.",
                "steps": ["Check context", "Record result"],
                "required_context": "incident",
                "risk_level": "low",
            },
            headers={"X-OpsForge-Actor": "pytest"},
        )
        runbook = runbook_response.json()
        execution_response = client.post(
            f"/api/runbooks/{runbook['key']}/execute",
            json={
                "incident_id": incident["id"],
                "requested_by": "pytest",
                "outcome": "success",
                "notes": "Dependency is healthy.",
                "completed_steps": [0, 1],
            },
        )
        logs = client.get("/api/audit-logs").json()

    assert runbook_response.status_code == 201
    assert runbook["steps"] == ["Check context", "Record result"]
    assert execution_response.status_code == 200
    assert execution_response.json()["status"] == "success"
    assert execution_response.json()["output"] == "Dependency is healthy."
    assert any(
        log["action"] == "incident.runbook_executed"
        and log["entity_id"] == incident["id"]
        for log in logs
    )


def test_manual_runbook_cannot_report_success_with_incomplete_steps() -> None:
    with _client() as client:
        backup = next(
            item
            for item in client.get("/api/runbooks").json()
            if item["key"] == "diagnostic_echec_sauvegarde"
        )
        service = _create_service(client, slug="manual-incomplete")
        incident = _create_manual_incident(client, service["id"])
        response = client.post(
            f"/api/runbooks/{backup['key']}/execute",
            json={
                "incident_id": incident["id"],
                "requested_by": "pytest",
                "outcome": "success",
                "completed_steps": [0],
            },
        )

    assert response.status_code == 200
    assert response.json()["status"] == "failed"
    assert "Toutes les étapes" in response.json()["output"]


def test_arbitrary_automation_key_is_rejected() -> None:
    with _client() as client:
        response = client.post(
            "/api/runbooks",
            json={
                "key": "unsafe_candidate",
                "name": "Unsafe candidate",
                "mode": "automated",
                "automation_key": "shell_command",
                "required_context": "none",
                "risk_level": "high",
            },
        )

    assert response.status_code == 422
    assert "liste approuvée" in response.json()["detail"]


def test_runbook_execution_is_available_through_history_api() -> None:
    with _client() as client:
        service = _create_service(client, slug="history-service")
        execution = client.post(
            "/api/runbooks/health_check_service/execute",
            json={"service_id": service["id"], "requested_by": "pytest"},
        ).json()
        history = client.get("/api/runbook-executions")

    assert history.status_code == 200
    assert any(item["id"] == execution["id"] for item in history.json())
